### ISSUE TITLE
Document OpenShift registry configuration such that OpenShift will treat its own external route as a trusted image source that can pull images anonymously.

### ISSUE THREAD

**Issue by magreenberg** [rhilconsultants/openshift#85]

**Comment by ooichman** [comment]
after exposing a route we need to make sure we take the following steps : 

1. create a certificate for the wildcard A record (route) : 
https://two-oes.medium.com/working-with-openssl-and-dns-alternative-names-367f06a23841?sk=28bf711fe07e62e407de071a9f8397b7

2.  update the cluster CA list
https://two-oes.medium.com/openshift-4-in-an-air-gap-disconnected-environment-part-3-customization-4b315dd17316?sk=e247251c75455327e9b845c96c8e6762

3.  update the default route certificate 
https://two-oes.medium.com/openshift-4-in-an-air-gap-disconnected-environment-part-3-customization-4b315dd17316?sk=e247251c75455327e9b845c96c8e6762

4.  adding the registry to the cluster : 
https://two-oes.medium.com/disconnected-openshift-4-with-internal-registry-a5542fa167c?sk=30f49c66f65ac0176dbd31ac93ff2ed6
